Guide page for testing - first draft
tannerlinsley/react-query pull request #1244
Opened 2020-11-02 08:49 UTC by sazzer

I can't promise it's the best written documentation page, but it's a starting point for people to read to understand how they can test their code that makes use of React Query :)

Cheers

2020-11-02 14:51 UTC, tannerlinsley commented
It looks great! Maybe we could use the isLoading/isSuccess from the query instead of waiting on the nock status?

2020-11-02 16:29 UTC, sazzer commented
Hi there,

To be honest, the code I've got here was lifted almost as-is from my own
project, and because I'm using *Suspense* I didn't make use fo the
isLoading/isSuccess stuff.
I'll have a look at re-working it to use that for you tomorrow though.

Cheers

On Mon, 2 Nov 2020 at 14:52, Tanner Linsley <notifications@github.com>
wrote:

> It looks great! Maybe we could use the isLoading/isSuccess from the query
> instead of waiting on the nock status?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tannerlinsley/react-query/pull/1244#issuecomment-720519133>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAQEGA3IEF7EKKLNDOUC43SN3BRJANCNFSM4THF6VKA>
> .
>

2020-11-03 21:36 UTC, tannerlinsley requested changes

2020-11-03 21:36 UTC, tannerlinsley commented on docs/src/pages/docs/guides/testing.md
> +  return expectation.isDone();
```suggestion
  return result.current.isSuccess();
```

2020-11-03 21:36 UTC, tannerlinsley approved these changes

2020-11-03 21:39 UTC, merged

2020-11-05 16:22 UTC, tannerlinsley commented
:tada: This PR is included in version 2.26.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-query/v/2.26.2)
- [GitHub release](https://github.com/tannerlinsley/react-query/releases/tag/v2.26.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-11-15 09:42 UTC, tannerlinsley commented
:tada: This PR is included in version 3.2.0-beta.24 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/react-query/v/3.2.0-beta.24)
- [GitHub release](https://github.com/tannerlinsley/react-query/releases/tag/v3.2.0-beta.24)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: