Binded class methods so its possible to destruct queryClient object w…
tannerlinsley/react-query pull request #1586
Opened 2021-01-06 20:06 UTC by lrdass

closes #1575 
Simple fix so that the  `queryClient` object is now destructable.
Just binded every class method

2021-01-09 20:25 UTC, tannerlinsley commented
What does this do to bundle size?

2021-02-12 20:06 UTC, tannerlinsley commented
@boschni What are your thoughts here?

2021-03-17 12:10 UTC, lrdass commented
> @boschni What are your thoughts here?

To be honest, I don't know the "standart" way to measure this precisily.
So I've done a `du -h` of `/lib` after building it.

results are:
before
 ```
   8,0K    lib/persist-localstorage-experimental
   72K lib/
    68K lib/react
   16K lib/hydration
   132K    lib/core
   304K    lib/
```

and  after the changes
```
8,0K	lib/persist-localstorage-experimental
72K	lib/devtools
68K	lib/react
16K	lib/hydration
136K	lib/core
308K	lib/

```

2021-03-30 23:46 UTC, tannerlinsley requested changes
If my memory serves me well, shouldn't we be able to auto-bind these class methods with the `method = () => {}` syntax?

```js
class Tanner {
  posts: Array<any>

  constructor () {
    this.posts = []
  }

  getPosts = () => {
    return this.posts
  }
}

const tanner = new Tanner()

const {
  getPosts
} = tanner

getPosts()
```

2021-03-30 23:51 UTC, lrdass commented
> If my memory serves me well, shouldn't we be able to auto-bind these class methods with the `method = () => {}` syntax?
> 
> ```js
> class Tanner {
>   posts: Array<any>
> 
>   constructor () {
>     this.posts = []
>   }
> 
>   getPosts = () => {
>     return this.posts
>   }
> }
> 
> const tanner = new Tanner()
> 
> const {
>   getPosts
> } = tanner
> 
> getPosts()
> ```

Yea, it would! Going to work on it.

2021-03-31 09:12 UTC, boschni commented
Public class fields will eventually generate the same amount of code. Usually class methods are not bound, which means you cannot do something like `const { toISOString }  = new Date()`. I'm fine with that behavior, but if we really want to bind them you can create a `bindAll` utility function to automatically bind all methods.

2021-05-07 15:48 UTC, closed without merging