feat(quick-start): improved guide
tannerlinsley/react-query pull request #2704
Opened 2021-09-22 19:25 UTC by akashshyamdev

Based on issue #2669

2021-09-27 12:09 UTC, akashshyamdev commented
@TkDodo @tannerlinsley   Is everything all right... are there any other issues/contributions I can take?

2021-09-27 13:03 UTC, TkDodo commented
Thanks for the contribution. I think we have to work on the wording a little bit, but I haven't gotten around to it yet, sorry

2021-09-27 14:03 UTC, akashshyamdev commented
@TkDodo cool... could you let me know where it feels off and I'll rewrite that

2021-10-03 07:50 UTC, TkDodo requested changes
I don't really like that the quick start now shows the same example 3 times, always getting bigger, always repeating itself. Without something like line highlighting, it will get difficult to understand what has been added.

How about we just extend the comments that we already have in the code a little bit instead of adding paragraphs underneath it? Most of the descriptions are also a bit self-explanatory, like:

> We have a button, which on being clicked triggers ...

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> -      <Todos />
i think it's a bit weird that we provide an example that is not really runnable. Rendering a `QueryClientProvider` without `children` isn't even valid jsx ....

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> +Here we are creating a client by creating a new instance of the `QueryClient` class.
`creating a client by creating ...` is a bit repetitive.

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> +A query client can be used to deal with things like cache.
```suggestion
A QueryClient can be used to interact directly with the underlying caches.
```

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> +A `query` listens to a source of data, in our case, the `getTodos` method.
this makes it sound like we're listening to the function `getTodos`, which is not true. We're listening to the query key, not the function. It gives the impression that the functional reference must be stable, which it is here, but it doesn't have to be.

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> +Queries are generally use with the `GET` HTTP method, mutations are used for HTTP methods like `POST`, `PUT` etc which modify data on the server.
this is not a requirement and I wouldn't put it on the first page. react-query is promise based, so everything that produces a promise is welcome. It doesn't even have to fetch data over a network at all, and e.g. graphql exclusively uses POST requests for everything ....

2021-10-03 07:50 UTC, TkDodo commented on docs/src/pages/quick-start.md
> +  const queryClient = useQueryClient();
this is just inconsistent now:

```suggestion
  const queryClient = useQueryClient()
```

2021-10-08 03:43 UTC, akashshyamdev commented
@TkDodo I've made the necessary changes, let me know if it's alright. If everything's good, could you mark this PR as `hacktoberfest-accepted`?

2021-11-13 09:12 UTC, TkDodo commented
sorry, I don't think this is making the guide any better than it currently is. I'll try to make the docs code blocks better, maybe with line highlighting and then we can revisit this.

2021-11-13 09:12 UTC, closed without merging