feat: add optional functions to serialize and deserialize from Storage Persistors
tannerlinsley/react-query pull request #2864
Opened 2021-10-31 14:28 UTC by bengry

Right now the (experimental) persistor functionality or at least the two built-in ones use simple JSON `stringify` and `parse`.
This is fine, but I'd like to get some more control over the serialization and deserialization of the data.
For example, the data I store in `react-query`'s cache is already JS objects which are not valid JSON in some cases - e.g. `Date` reviving upon `fetch`ing from the server:
```js
const data = fetch('https://my-api.com')
.then(response => response.text())
.then(text => JSON.parse(text, dateReviver); // see https://gist.github.com/davehax/2f32e7b09c3da3531601e6543fcff82e for an example for a `dateReviver` implementation
```

More details in https://github.com/tannerlinsley/react-query/discussions/2771

2021-10-31 18:52 UTC, TkDodo requested changes
please also update the docs :)

2021-10-31 18:52 UTC, TkDodo commented on src/createAsyncStoragePersistor-experimental/index.ts
> +  * @defualt `JSON.stringify`
```suggestion
  * @default `JSON.stringify`
```

2021-10-31 18:52 UTC, TkDodo commented on src/createAsyncStoragePersistor-experimental/index.ts
> +   * @defualt `JSON.parse`
```suggestion
   * @default `JSON.parse`
```

2021-10-31 18:52 UTC, TkDodo commented on src/createWebStoragePersistor-experimental/index.ts
> +  * @defualt `JSON.stringify`
```suggestion
  * @default `JSON.stringify`
```

2021-10-31 18:52 UTC, TkDodo commented on src/createWebStoragePersistor-experimental/index.ts
> +   * @defualt `JSON.parse`
```suggestion
   * @default `JSON.parse`
```

2021-10-31 18:53 UTC, TkDodo commented
also, there are type errors. please see the CI pipeline.

2021-10-31 19:09 UTC, bengry commented
> also, there are type errors. please see the CI pipeline.

So much for copy-pasting an issue written on mobile, and for giving https://vscode.dev a try...
Sorry for the hassle.

I fixed the issues in the latest iteration.

I'll push an update to the docs in a bit.

2021-10-31 19:48 UTC, TkDodo approved these changes
that looks good, thank you 👍

2021-10-31 20:00 UTC, merged

2021-10-31 20:05 UTC, tannerlinsley commented
:tada: This PR is included in version 3.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-query/v/3.31.0)
- [GitHub release](https://github.com/tannerlinsley/react-query/releases/tag/v3.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-02-10 08:03 UTC, hverlin commented
Thanks for adding this option @bengry @TkDodo 

One common use case for this, I think, is to use compression/decompression when one hits the limit of what can be stored in local storage.

Here is an example using the `lz-string` library (https://pieroxy.net/blog/pages/lz-string/index.html)

```js
import { QueryClient } from 'react-query';
import { persistQueryClient } from 'react-query/persistQueryClient-experimental';
import { createWebStoragePersistor } from 'react-query/createWebStoragePersistor-experimental';

import { compress, decompress } from 'lz-string';

const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: Infinity } } });

persistQueryClient({
  queryClient: connectionsQueryClient,
  persistor: createWebStoragePersistor({
    storage: window.localStorage,
    serialize: data => compress(JSON.stringify(data)),
    deserialize: data => JSON.parse(decompress(data)),
  }),
  maxAge: Infinity,
});
```

Not sure if it makes to sense to add it to the documentation?

2022-02-10 08:25 UTC, TkDodo commented
Oh yes please - add it to the documentation of v4 please, as the plugin becomes "stable" then :)

2022-02-10 08:41 UTC, hverlin commented
:+1: maybe another option is to use `createAsyncStoragePersistor` and create a custom storage implementation for `indexedDb`